name: Build on Ubuntu
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install jq tool
        run: |
          sudo apt-get update
          sudo apt-get install jq

      - name: Download ngrok
        run: |
          wget -q https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip
          unzip -qq ngrok-stable-linux-amd64.zip
          
      - name: Auth
        run: ./ngrok authtoken 2dUvkmsD58L7yOoqgKugNtmkMdW_5xWrH7Xaz1MtdSKtixbFq
      
      - name: Enable RDP
        run: |
          sudo ufw allow 3389/tcp
          sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo service ssh restart
          
      - name: Create Tunnel
        run: ./ngrok tcp 3389
